### ISSUE TITLE
PiHole: Unable to resolve hostname

### ISSUE THREAD

**Issue by HOGGL** [samizdapp/skunkworks#5]
When starting pihole1 it errors out saying "Unable to resolve host, name or service not known".
Running `nslookup $HOSTNAME` works in balneaOS but not in a container with options `--privileged`, `--network host` and `--dns 127.0.0.1`. There it times out.
Is this a firewall issue? I would've thought docker host networking would skip that for local communication.

There's also another issue, dnsmasq is unable to assign to the 10.0.0.0 network configured here:
I assume this is meant to be the wireguard network of 10.128.0.0/31?
https://github.com/samizdapp/skunkworks/blob/b1746bcf6adf7b5e7b132dde0f89333157a3d731/docker-compose.yml#L57

**Comment by HOGGL** [comment]
Running `nc -v 127.0.0.1 53` responds with "netcat: connect to 127.0.0.1 port 53 (tcp) failed: Connection refused". So there probably is an iptables rule somewhere but after running `systemctl stop iptables` the issue still remains. I've also added blanket ACCEPT all rules to the docker and balena chains.

**Comment by rynomad** [comment]
Is this issue still current? Based on timestamp it may have been resolved by recent commits.

**Comment by HOGGL** [comment]
I just checked and I'm still having a similar issue but this time PiHole starts. I think this issue is related to #1 because both issues only happen on balenaOS.

Running skunkworks in a VM:
- In the logs: `::: Testing pihole-FTL DNS: FTL started!`
- PiHole remains running

Running in balenaOS:
- In the logs: `::: Testing pihole-FTL DNS: sudo: unable to resolve host 02f38ea: Name or service not known`
- The container restarts every two minutes

So I think pihole-FTL exits or crashes because it's unable to resolve, the init supervisor seeing this thinking it's an ordinary exit, brings down the container.

Do you get the same error in your logs?

**Comment by HOGGL** [comment]
I added `echo -e "127.0.1.1\t$HOSTNAME" >> /etc/hosts`  to 10-custom.sh, this fixes the error message but the container still restarts. I don't know if this is the best way to fix it but Ubuntu has this line.
